title: Product Engineering Intern
orgName: Meridian Knowledge Solutions
orgSite: https://meridianks.com/
startDate: 2022/05
description: I work with testing tools, such as Selenium and TestProject, to
  write and verify user interface test automation for under-development versions
  of the learning management system.
