role: Software Development Engineer in Test Intern
title: Meridian Knowledge Solutions
website: https://meridianks.com/
startDate: 2022/05
endDate: 2022/08
description: Migrated Selenium software testing suite of over 50 smoke,
  end-to-end, and integration tests to the newly adopted TestProject
  collaboration platform. Collaborated with team of over 20 engineers; exposed
  to the Agile Scrum workflow in professional environment.
