role: Product Engineering Intern
title: Meridian Knowledge Solutions
website: https://meridianks.com/
startDate: 2022/05
endDate: 2022/08
description: Migrated software testing suite (50+ smoke, end-to-end,
  integration, functional tests) from Selenium to TestProject. Collaborated in
  team of >20; adapted to Agile/Scrum workflow to improve productivity and
  accountability in a professional environment.
