title: Product Engineering Intern
orgName: Meridian Knowledge Solutions
orgSite: https://meridianks.com/
startDate: 2022/05
endDate: 2022/08
description: "Migrated software testing suite (50+ smoke, end-to-end,
  integration, functional tests) from Selenium to TestProject. Collaborated with
  team of 20+: learned Agile Scrum workflow in practice. "
